name: "CI"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker:
    runs_on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GHCR
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.test
